// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"realword/internal/biz"
	"realword/internal/conf"
	"realword/internal/data"
	"realword/internal/server"
	"realword/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	profileRepo := data.NewProfileRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, profileRepo, logger)
	articleRepo := data.NewArticleRepo(dataData, logger)
	commentRepo := data.NewCommentRepo(dataData, logger)
	tagRepo := data.NewTagRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, commentRepo, tagRepo, logger)
	realWordService := service.NewRealWordService(userUsecase, articleUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, realWordService, logger)
	grpcServer := server.NewGRPCServer(confServer, realWordService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
